---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./staging
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  namespace: flux-system
  name: production
spec:
  interval: 1m0s
  path: ./production
  prune: false
  # suspend: true
  sourceRef:
    kind: GitRepository
    name: flux-system
