apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: production
spec:
  interval: 5m0s
  path: ./deploy1
  prune: false
  suspended: true
  sourceRef:
    kind: GitRepository
    name: flux-system
